import {
  Baby,
  Banknote,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  Car,
  Dumbbell,
  GraduationCap,
  HeartPulse,
  Home,
  MoreHorizontal,
  PawPrint,
  Plane,
  Popcorn,
  ReceiptText,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Tv,
  Utensils,
  Wifi,
  type LucideIcon,
} from "lucide-react";

export const defaultExpenseCategories = [
  "Alimentacao",
  "Mercado",
  "Moradia",
  "Transporte",
  "Combustivel",
  "Saude",
  "Educacao",
  "Lazer",
  "Assinaturas",
  "Internet",
  "Telefone",
  "Roupas",
  "Viagem",
  "Pets",
  "Filhos",
  "Academia",
  "Impostos",
  "Seguro",
  "Trabalho",
  "Outras",
];

export const categoryIconMap: Record<string, LucideIcon> = {
  Alimentacao: Utensils,
  "Alimentação": Utensils,
  Mercado: ShoppingBasket,
  Moradia: Home,
  Transporte: Bus,
  Combustivel: Car,
  Combustível: Car,
  Saude: HeartPulse,
  Saúde: HeartPulse,
  Educacao: GraduationCap,
  Educação: GraduationCap,
  Lazer: Popcorn,
  Assinaturas: Tv,
  Internet: Wifi,
  Telefone: Smartphone,
  Roupas: Shirt,
  Viagem: Plane,
  Pets: PawPrint,
  Filhos: Baby,
  Academia: Dumbbell,
  Impostos: Banknote,
  Seguro: ShieldCheck,
  Trabalho: BriefcaseBusiness,
  Livros: BookOpen,
  Beleza: Sparkles,
  Contas: ReceiptText,
  Outras: MoreHorizontal,
};

export function getCategoryIcon(category?: string | null) {
  return category ? categoryIconMap[category] ?? MoreHorizontal : MoreHorizontal;
}
